-- create database git_data;
-- use git_data;
-- create table github_profiles(id int auto_increment primary key , candidate_id int not null ,github_id bigint not null ,github_username varchar(100) not null , bio text null ,company varchar(266) null ,location varchar(255) null ,public_repos int not null default 0 ,followers int not null default 0,account_created_at datetime null,last_fetched_at datetime not null )
-- create table github_repos(id int auto_increment primary key ,github_profile_id int not null ,github_repo_id bigint not null,name varchar(255) not null,description text null , primary_language varchar(100) null ,is_fork boolean not null default false,stargazers_count int not null default 0,forks_count int not null default 0,open_issues_count int not null default 0,size_kb int not null default 0,license_key varchar(50) null ,homepage_url varchar (500) null ,topics json null,repo_created_at datetime null ,repo_updated_at datetime null ,repo_pushed_at datetime null ,fetched_at datetime not null ,foreign key (github_profile_id)  references github_profiles(id) on update cascade  on delete restrict);
-- select * from github_profiles
-- select * from github_repos
-- use git_data
-- CREATE TABLE candidates (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     full_name VARCHAR(255) NOT NULL,
--     email VARCHAR(255) NULL,
--     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- select * from candidates
-- alter table github_profiles add constraint fk_github_profile_candidate foreign key (candidate_id) references candidates(id) on update cascade on delete restrict

-- use git_data
-- select * from candidates
-- select * from github_profiles
-- DELETE FROM github_profiles 
-- WHERE id BETWEEN 20 AND 38;
-- select * from github_profiles
-- select * from github_repos
-- use git_data
-- create table resumes (id int auto_increment primary key,candidate_id int not null unique ,full_name varchar(200) null,email varchar(200) null,phone varchar (50) null ,location varchar (200) null, github_url VARCHAR(500) NULL,
--     linkedin_url VARCHAR(500) NULL,
--     skills JSON NULL,
--     certifications JSON NULL,
--     education JSON NULL,
--     projects JSON NULL,raw_text LongText Null,uploaded_at datetime not null default current_timestamp,parsed_At Datetime null ,foreign key (candidate_id) references candidates(id) on update cascade on delete restrict);
-- select * from candidates where id =2
-- TRUNCATE TABLE resumes
-- SET FOREIGN_KEY_CHECKS = 0;
-- TRUNCATE TABLE github_profiles
-- TRUNCATE TABLE github_repos
-- TRUNCATE TABLE candidates
-- SET FOREIGN_KEY_CHECKS = 1;
-- select * from github_repos
-- select * from github_profiles
-- insert into candidates (full_name,email) values ("Scope","scope@gmail.com");
-- select * from candidates
-- select projects from resumes
-- use git_data
-- alter table resumes add experience varchar(200) null
-- select * from resumes 
-- use git_data
-- ALTER TABLE resumes MODIFY COLUMN experience JSON;
-- select * from resumes
-- select * from github_repos
-- select * from github_profiles
-- CREATE TABLE  portfolio_scores (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     candidate_id INT UNIQUE NOT NULL,
--     portfolio_score FLOAT NOT NULL,
--     total_repos INT DEFAULT 0,
--     live_projects_count INT DEFAULT 0,
--     primary_languages JSON,
--     strengths JSON,
--     weaknesses JSON,
--     calculated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
-- );
-- select * from resumes
-- select * from resumes
-- select * from resumes
-- Select * from resumes where candidate_id = 1
-- select * from portfolio_scores
-- select * from github_repos
-- select * from portfolio_scores
-- select * from github_repos
-- select * from portfolio_scores
-- select * from portfolio_scores
-- SELECT * FROM github_profiles 
-- use git_data
-- CREATE TABLE ats_reports (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     candidate_id INT UNIQUE NOT NULL,
--     overall_score INT NOT NULL,
--     contact_score INT,
--     summary_score INT,
--     skills_score INT,
--     experience_score INT,
--     education_score INT,
--     projects_score INT,
--     certifications_score INT,
--     formatting_score INT,
--     strengths JSON,
--     weaknesses JSON,
--     missing_sections JSON,
--     keyword_matches JSON,
--     missing_keywords JSON,
--     suggestions JSON,
--     hiring_recommendation VARCHAR(50),
--     calculated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
-- );
-- select * from ats_reports
-- select * from github_profiles
-- CREATE TABLE candidate_final_scores (
--     candidate_id INT PRIMARY KEY,
--     portfolio_quality FLOAT,
--     project_experience FLOAT,
--     engineering_readiness FLOAT,
--     communication FLOAT,
--     leadership FLOAT,
--     hiring_confidence FLOAT,
--     calculated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
-- );
-- select * from portfolio_scores
-- select * from ats_reports
-- use git_data
-- create table jobs(id int auto_increment primary key,title varchar(255) not null ,
-- company varchar(255) not null,
-- job_type enum('Full-Time', 'Remote', 'Freelance', 'Client', 'Internal', 'Startup') NOT NULL,
-- required_skills json not null ,description text null,
-- location varchar(255) null,posted_ad datetime not null default current_timestamp);
-- create table job_matches( id INT AUTO_INCREMENT PRIMARY KEY,
--     candidate_id INT NOT NULL,
--     job_id INT NOT NULL,
--     match_score FLOAT NOT NULL,
--     matched_skills JSON NOT NULL,
--     missing_skills JSON NOT NULL,
--     calculated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     unique key unique_candidate_job (candidate_id,job_id),
--     foreign key (candidate_id) references candidates(id) on update cascade on delete restrict,
--     foreign key (job_id) references jobs(id) on update cascade on delete restrict);
-- INSERT INTO jobs (title, company, job_type, required_skills, description, location) VALUES
-- ('Junior ML Engineer', 'TechCorp', 'Full-Time', '["Python", "Scikit-learn", "Pandas", "NumPy", "Machine Learning"]', 'Build and deploy ML models.', 'Karachi'),
-- ('Data Analyst', 'DataFlow', 'Remote', '["Python", "SQL", "Pandas", "Matplotlib", "Seaborn"]', 'Analyze and visualize business data.', 'Remote'),
-- ('AI Engineer Intern', 'AI Startup', 'Startup', '["Python", "Deep Learning", "RAG Pipelines", "Git"]', 'Work on cutting-edge AI systems.', 'Karachi'),
-- ('Backend Developer', 'WebCo', 'Full-Time', '["Python", "FastAPI", "SQL", "Docker", "REST API"]', 'Build scalable APIs.', 'Remote');
-- set foreign_key_checks  = 1
-- select * from jobs
select * from resumes